### PR TITLE
fix(mempool): reject invalid AA txs to prevent mempool DOS

### LINKED ISSUE #1009: Bug: Tx Pool can be DOSed via AA txs
### Describe the bug

The tx pool can be permanently DOSed with AA txs. AA txs with far future `valid_after` timestamps permanently occupy mempool, and will never be executed or evicted

### PR DESCRIPTION
**Pull request by 0xrusowsky**
## Motivation

closes #1009 

## Solution

as proposed in the issue discussion, we reject txs which have a `valid_after` beyond a `const AA_VALID_AFTER_MAX_SECS`.

## Questions

- is 1h a good value?

### CODE REVIEW

File: crates/transaction-pool/src/validator.rs [hunk 1]
```diff
@@ -11,6 +11,10 @@ use reth_transaction_pool::{
 };
 use tempo_revm::TempoStateAccess;
 
+// Reject AA transactions where `valid_after` is too far in the future to prevent mempool DOS.
+// ref: <https://github.com/tempoxyz/tempo/issues/1009>
+const AA_VALID_AFTER_MAX_SECS: u64 = 3600;
```
Comment (mattsse) [inline crates/transaction-pool/src/validator.rs]: this is 6 hrs?

File: crates/transaction-pool/src/transaction.rs [hunk 2]
```diff
@@ -81,6 +84,7 @@ impl PoolTransactionError for TempoPoolTransactionError {
             Self::ExceedsNonPaymentLimit => false,
             Self::InvalidFeeToken(_) => false,
             Self::MissingFeeToken => false,
+            Self::InvalidValidAfter { .. } => true,
```
Comment (mattsse) [inline crates/transaction-pool/src/transaction.rs]: this should also be false here imo

because this is still a good tx technically, just not yet

File: crates/transaction-pool/src/validator.rs (hunk 1 above)
Comment (0xrusowsky) [reply crates/transaction-pool/src/validator.rs]: as discussed in dms, will turn it into a configurable param

File: crates/transaction-pool/src/validator.rs [hunk 3]
```diff
@@ -11,6 +13,14 @@ use reth_transaction_pool::{
 };
 use tempo_revm::TempoStateAccess;
 
+/// Maximum allowed `valid_after` offset for AA transactions (in seconds).
+static AA_VALID_AFTER_MAX_SECS: LazyLock<u64> = LazyLock::new(|| {
+    std::env::var("AA_VALID_AFTER_MAX_SECS")
```
Comment (mattsse) [inline crates/transaction-pool/src/validator.rs]: let's not introduce env vars for settings

this should be a field in the validator instead and can be wired to the cli via TempoArgs but we can also do that later

Comment (0xrusowsky) [reply crates/transaction-pool/src/validator.rs]: addressed in [`e5da853` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/e5da853c4512f8c4547f5d77f729fa77142cd623)

File: bin/tempo/src/main.rs [hunk 4]
```diff
@@ -36,10 +36,28 @@ use tempo_faucet::{
...
+};
 use tokio::sync::oneshot;
 use tokio_util::either::Either;
 
+/// Transaction pool validator CLI arguments.
+#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::Args)]
+struct ValidatorArgs {
+    /// Maximum allowed `valid_after` offset for AA txs.
+    #[arg(long, default_value_t = DEFAULT_AA_VALID_AFTER_MAX_SECS)]
+    pub aa_valid_after_max_secs: u64,
```
Comment (mattsse) [inline bin/tempo/src/main.rs]: let's prefix this with "txpool." see also TxpoolArgs

File: bin/tempo/src/main.rs [hunk 5]
```diff
@@ -36,10 +36,28 @@ use tempo_faucet::{
...
-use tempo_node::{TempoFullNode, node::TempoNode};
+use tempo_node::{
+    DEFAULT_AA_VALID_AFTER_MAX_SECS, TempoFullNode, ValidatorConfig, node::TempoNode,
+};
 use tokio::sync::oneshot;
 use tokio_util::either::Either;
 
+/// Transaction pool validator CLI arguments.
+#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::Args)]
+struct ValidatorArgs {
```
Comment (mattsse) [inline bin/tempo/src/main.rs]: we can name this TempTxPoolArgs

this should be moved below the main type and made a pub

File: crates/transaction-pool/src/validator.rs [hunk 6]
```diff
@@ -61,6 +69,28 @@ where
             );
         }
 
+        // Reject AA transactions where `valid_after` is too far in the future to prevent mempool DOS.
+        if let Some(tx) = transaction.inner().as_aa()
+            && let Some(valid_after) = tx.tx().valid_after
+        {
+            let current_time = std::time::SystemTime::now()
```
Comment (klkvr) [inline crates/transaction-pool/src/validator.rs]: we could also use `self.inner.fork_tracker().tip_timestamp()` to get the latest block timestamp, not sure what's better here

File: crates/transaction-pool/src/validator.rs [hunk 7]
```diff
@@ -61,6 +69,28 @@ where
...
+                .duration_since(std::time::UNIX_EPOCH)
+                .expect("system time before UNIX EPOCH")
+                .as_secs();
+            let max_allowed = current_time.saturating_add(self.aa_valid_after_max_secs);
+            if valid_after > max_allowed {
```
Comment (klkvr) [inline crates/transaction-pool/src/validator.rs:215]: I think we also need to check `valid_before` here

Comment (0xrusowsky) [reply crates/transaction-pool/src/validator.rs:215]: yup, this is addressed in #1055

File: bin/tempo/src/main.rs (hunk 5 above)
Comment (0xrusowsky) [reply bin/tempo/src/main.rs]: addressed in [`9bb86d6` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/9bb86d6ffe147dd0512acee1a469d9df8d0ca057)

File: bin/tempo/src/main.rs (hunk 4 above)
Comment (0xrusowsky) [reply bin/tempo/src/main.rs]: addressed in [`9bb86d6` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/9bb86d6ffe147dd0512acee1a469d9df8d0ca057)

File: crates/transaction-pool/src/validator.rs (hunk 6 above)
Comment (0xrusowsky) [reply crates/transaction-pool/src/validator.rs]: @mattsse thoughts?

File: crates/node/src/node.rs [hunk 8]
```diff
@@ -41,19 +41,42 @@ use tempo_payload_types::TempoPayloadAttributes;
...
 
+/// Default maximum allowed `valid_after` offset for AA txs (1 hour).
+pub const DEFAULT_AA_VALID_AFTER_MAX_SECS: u64 = 3600;
+
+/// Validator configuration.
+#[derive(Debug, Clone, Copy, PartialEq, Eq)]
+pub struct ValidatorConfig {
+    /// Maximum allowed `valid_after` offset for AA txs.
+    pub aa_valid_after_max_secs: u64,
+}
```
Comment (0xKitsune) [inline crates/node/src/node.rs]: Do we need a separate config for this? Or can this simply be a field on the `TempoPoolBuilder`?

File: crates/transaction-pool/src/validator.rs (hunk 6 above)
Comment (0xKitsune) [reply crates/transaction-pool/src/validator.rs]: This is probably fine in most cases IMO we should use `tip_timestamp()` as we can not assume `SystemTime::now()` is monotonic. It can jump backward/forward due to NTP, VM clock drift, etc. and hit a panic due to the expect here.

File: crates/node/src/node.rs (hunk 8 above)
Comment (0xrusowsky) [reply crates/node/src/node.rs]: will integrate on `TempoPoolBuilder`, as that will align better with the changes that mattsse requested for the CLI inputs

Comment (0xrusowsky) [reply crates/node/src/node.rs]: address with [`fe5d007` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/fe5d00761ce5cd5b2be6f360c66e840634461ead)

File: crates/transaction-pool/src/validator.rs (hunk 6 above)
Comment (0xrusowsky) [reply crates/transaction-pool/src/validator.rs]: addressed with [`edc0252` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/edc0252e1ff66df411682ff29026abceff57e097)

File: crates/transaction-pool/src/maintain.rs [hunk 9]
```diff
@@ -0,0 +1,81 @@
...
+use reth_transaction_pool::{PoolTransaction, TransactionPool};
+use std::collections::BTreeMap;
+use tracing::debug;
+
+/// Spawns a background task that evicts expired AA transactions.
+///
+/// - Listens for new blocks to get chain timestamp
+/// - Listens for new transactions to track `valid_before` timestamps
+/// - Evicts transactions when `valid_before <= tip_timestamp`
+pub async fn evict_expired_aa_txs<P, C>(pool: P, client: C)
```
Comment (klkvr) [inline crates/transaction-pool/src/maintain.rs:23]: seems that when we spawn this we're racing with backup task which re-inserts all txs from disk into the pool

this means that if backup txs will be re-inserted before this is spawned, we will miss some of them

I guess what we could do here is start by loading all txs from the pool and inserting them into the `expiry_map`

Comment (0xrusowsky) [reply crates/transaction-pool/src/maintain.rs:23]: i see, makes sense. will fix it

Comment (0xrusowsky) [reply crates/transaction-pool/src/maintain.rs:23]: addressed in [`f4575e6` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/f4575e6b6196c6a56d76043e54184704632c0bb7)

File: bin/tempo/src/main.rs [hunk 10]
```diff
@@ -188,7 +208,7 @@ fn main() -> eyre::Result<()> {
             node,
             node_exit_future,
         } = builder
-            .node(TempoNode::new())
+            .node(TempoNode::new(args.tx_pool_args.into()))
```
Comment (mattsse) [inline bin/tempo/src/main.rs]: this conversion will lead do some additional refactor work in case we need more settings not limited to the pool, imo it'd be easier to just propagate the settings/args here

File: crates/node/src/node.rs [hunk 11]
```diff
@@ -41,19 +41,27 @@ use tempo_payload_types::TempoPayloadAttributes;
...
-    pub const fn new() -> Self {
-        Self
+    pub fn new(tx_pool_config: TempoPoolBuilder) -> Self {
+        Self { tx_pool_config }
     }
 
     /// Returns a [`ComponentsBuilder`] configured for a regular Tempo node.
-    pub fn components<Node>() -> ComponentsBuilder<
+    pub fn components<Node>(
+        tx_pool_config: TempoPoolBuilder,
```
Comment (mattsse) [inline crates/node/src/node.rs]: this is misnamed

File: crates/transaction-pool/src/tasks.rs [hunk 12]
```diff
@@ -0,0 +1,92 @@
...
+                    .range(..=tip_timestamp)
+                    .map(|(ts, _)| *ts)
+                    .collect();
+
+                let mut to_remove = Vec::new();
+                for ts in expired {
+                    if let Some(hashes) = expiry_map.remove(&ts) {
+                        to_remove.extend(hashes);
+                    }
+                }
```
Comment (mattsse) [inline crates/transaction-pool/src/tasks.rs]: I believe you can simplify this with a

```
while let Some(entry) = expiry_map.first_entry() {

}
```

File: crates/transaction-pool/src/validator.rs [hunk 13]
```diff
@@ -466,4 +538,58 @@ mod tests {
...
+        let tx_no_valid_after = create_aa_transaction(None);
+        let validator = setup_validator(&tx_no_valid_after);
+        let outcome = validator
+            .validate_transaction(TransactionOrigin::External, tx_no_valid_after)
+            .await;
+
+        if let TransactionValidationOutcome::Invalid(_, err) = outcome {
+            let error_msg = format!("{err}");
+            assert!(
+                !error_msg.contains("valid_after timestamp")
```
Comment (fgimenez) [inline crates/transaction-pool/src/validator.rs]: is this string right? `valid_after` should be included but `timestamp`? if this string is wrong, then the assertion is always true `assert!(!false || anything) == assert!(true || anything) == ok`

File: crates/transaction-pool/src/validator.rs [hunk 14]
```diff
@@ -466,4 +538,58 @@ mod tests {
...
+        let tx_within_limit = create_aa_transaction(Some(current_time + 1800));
+        let validator = setup_validator(&tx_within_limit);
+        let outcome = validator
+            .validate_transaction(TransactionOrigin::External, tx_within_limit)
+            .await;
+
+        if let TransactionValidationOutcome::Invalid(_, err) = outcome {
+            let error_msg = format!("{err}");
+            assert!(
+                !error_msg.contains("valid_after timestamp")
```
Comment (fgimenez) [inline crates/transaction-pool/src/validator.rs]: same here

File: crates/transaction-pool/src/validator.rs [hunk 15]
```diff
@@ -466,4 +538,58 @@ mod tests {
             panic!("Expected Invalid outcome with InsufficientFunds error");
         }
     }
+
+    #[tokio::test]
+    async fn test_aa_valid_after_check() {
+        let current_time = std::time::SystemTime::now()
```
Comment (fgimenez) [inline crates/transaction-pool/src/validator.rs:577]: is it ok to use `SystemTime::now()` here? the validator will use `self.inner.fork_tracker().tip_timestamp()` which returns the mock provider's tip timestamp, this might be very far away (much smaller) than system time

Comment (0xrusowsky) [reply crates/transaction-pool/src/validator.rs:577]: addressed in [`da3cc46` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/da3cc46fd6f25e7bcddd871967a9836d9ee57b0e)

File: crates/transaction-pool/src/validator.rs (hunk 14 above)
Comment (0xrusowsky) [reply crates/transaction-pool/src/validator.rs]: addressed in [`da3cc46` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/da3cc46fd6f25e7bcddd871967a9836d9ee57b0e)

File: crates/transaction-pool/src/validator.rs (hunk 13 above)
Comment (0xrusowsky) [reply crates/transaction-pool/src/validator.rs]: good catch, without this error tests were failing!

addressed in [`da3cc46` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/da3cc46fd6f25e7bcddd871967a9836d9ee57b0e)

File: bin/tempo/src/main.rs (hunk 10 above)
Comment (0xrusowsky) [reply bin/tempo/src/main.rs]: addressed in [`ca4bc40` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/ca4bc404db5ddaae209a6bb156ef0902dc021a50)

File: crates/node/src/node.rs (hunk 11 above)
Comment (0xrusowsky) [reply crates/node/src/node.rs]: addressed in [`ca4bc40` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/ca4bc404db5ddaae209a6bb156ef0902dc021a50)

File: crates/transaction-pool/src/tasks.rs (hunk 12 above)
Comment (0xrusowsky) [reply crates/transaction-pool/src/tasks.rs]: addressed in [`285bc3c` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/285bc3ca8b735c3e6df10e75b66c056f100168ed)

File: crates/node/src/node.rs [hunk 16]
```diff
@@ -45,19 +45,47 @@ use tempo_transaction_pool::{
...
+/// Default maximum allowed `valid_after` offset for AA txs (1 hour).
+pub const DEFAULT_AA_VALID_AFTER_MAX_SECS: u64 = 3600;
+
+/// Tempo node CLI arguments.
+#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, clap::Args)]
+#[command(next_help_heading = "TxPool")]
+pub struct TempoNodeArgs {
+    /// Maximum allowed `valid_after` offset for AA txs.
+    #[arg(long = "txpool.aa-valid-after-max-secs", default_value_t = DEFAULT_AA_VALID_AFTER_MAX_SECS)]
+    pub aa_valid_after_max_secs: u64,
```
Comment (mattsse) [inline crates/node/src/node.rs:57]: this is better!

File: crates/transaction-pool/src/maintain.rs
Comment (mattsse) [inline crates/transaction-pool/src/maintain.rs:1]: nitpick, can we keep this as maintain.rs

File: crates/transaction-pool/src/maintain.rs [hunk 17]
```diff
@@ -0,0 +1,133 @@
...
+    // Track valid_before timestamp -> Vec<TxHash>
+    let mut expiry_map: BTreeMap<u64, Vec<TxHash>> = BTreeMap::new();
+
+    // Populate expiry map to prevent race condition at start-up
+    pool.all_transactions()
+        .all()
+        .for_each(|tx| track_expiry(&mut expiry_map, tx.inner().as_aa()));
+
+    // Subscribe to new transactions and blocks
+    let mut new_txs = pool.new_transactions_listener();
```
Comment (mattsse) [inline crates/transaction-pool/src/maintain.rs:45]: there's technically a smol race condition here, so this could be moved above the ` pool.all_transactions()` call

File: crates/transaction-pool/src/maintain.rs [hunk 18]
```diff
@@ -0,0 +1,133 @@
...
+            && let Some(valid_before) = aa_tx.tx().valid_before
+        {
+            let hash = *aa_tx.hash();
+            map.entry(valid_before).or_default().push(hash);
+        }
+    };
+
+    // Track valid_before timestamp -> Vec<TxHash>
+    let mut expiry_map: BTreeMap<u64, Vec<TxHash>> = BTreeMap::new();
+
```
Comment (mattsse) [inline crates/transaction-pool/src/maintain.rs:40]: I think we could sleep here for a sec or two just to give the backup task some time?

File: crates/transaction-pool/src/maintain.rs [hunk 19]
```diff
@@ -0,0 +1,133 @@
...
+        if let Some(aa_tx) = maybe_aa_tx
+            && let Some(valid_before) = aa_tx.tx().valid_before
+        {
+            let hash = *aa_tx.hash();
+            map.entry(valid_before).or_default().push(hash);
+        }
+    };
+
+    // Track valid_before timestamp -> Vec<TxHash>
+    let mut expiry_map: BTreeMap<u64, Vec<TxHash>> = BTreeMap::new();
```
Comment (mattsse) [inline crates/transaction-pool/src/maintain.rs:39]: I think this should be okay

File: crates/transaction-pool/src/maintain.rs (hunk 18 above)
Comment (0xrusowsky) [reply crates/transaction-pool/src/maintain.rs:40]: addressed in [`f3dd6c2` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/f3dd6c260134073ae78700c36eb7c2a8db010b49)

File: crates/transaction-pool/src/maintain.rs (hunk 17 above)
Comment (0xrusowsky) [reply crates/transaction-pool/src/maintain.rs:45]: addressed in [`f3dd6c2` (#1040)](https://github.com/tempoxyz/tempo/pull/1040/commits/f3dd6c260134073ae78700c36eb7c2a8db010b49)
