### PR TITLE
fix(tip20-factory): check tokenIdCounter in isTIP20

### LINKED ISSUE #1230: BUG: `is_tip20` in the rust impl, does not check tokenId
This issue was caught in the fuzz test CI, the solidity impl checks that an address is only considered `tip_20` if it's tokenId is less than the `tokenIdCounter` in the factory.
We don't have this check in the rust implementation right now.
```
  Location: crates/precompiles/src/tip20/mod.rs:43-45

  Solidity (docs/specs/src/TIP20Factory.sol:73-76):
  function isTIP20(address token) public view returns
  (bool) {
      return bytes12(bytes20(token)) ==
  0x20c000000000000000000000
          && uint64(uint160(token)) < tokenIdCounter;
  // ← checks tokenIdCounter
  }

  Rust (crates/precompiles/src/tip20/mod.rs:43-45):
  pub fn is_tip20(token: Address) -> bool {
      token.as_slice().starts_with(&TIP20_TOKEN_PREFIX)
      // ← MISSING: does NOT check if token_id <
  tokenIdCounter
  }

  Fix needed: The Rust is_tip20 function needs to also
  check that the token ID is less than tokenIdCounter.
```

### PR DESCRIPTION
**Pull request by fgimenez**
Closes #1230 

Fix `isTIP20` to check that token ID < `tokenIdCounter`, matching the Solidity implementation. Previously only checked the address prefix, allowing non-existent token IDs to pass validation.

### CODE REVIEW

File: crates/precompiles/src/tip20_factory/dispatch.rs [hunk 1]
```diff
@@ -33,7 +31,7 @@ impl<'a, S: PrecompileStorageProvider> Precompile for TIP20Factory<'a, S> {
                 })
             }
             ITIP20Factory::isTIP20Call::SELECTOR => {
-                view::<ITIP20Factory::isTIP20Call>(calldata, |call| Ok(is_tip20(call.token)))
+                view::<ITIP20Factory::isTIP20Call>(calldata, |call| self.is_tip20(call.token))
```
Comment (legion2002) [inline crates/precompiles/src/tip20_factory/dispatch.rs:34]: Should we need to hardfork gate this?

Comment (fgimenez) [reply crates/precompiles/src/tip20_factory/dispatch.rs:34]: i believe we don't need it, this is a view function that is not called by any other precompile. also the snapshot reexecution is passing

Comment (legion2002) [reply crates/precompiles/src/tip20_factory/dispatch.rs:34]: Yup makes sense

Comment (0xKitsune) [reply crates/precompiles/src/tip20_factory/dispatch.rs:34]: Given that this will not roll out until after public testnet, we should put this behind a hardfork. It is possible that within the time between public testnet launch and the hardfork, someone could deploy a contract that calls this function. Since we have an upcoming hardfork anyway, we can include this unless you think we need to roll this out sooner.

File: crates/precompiles/src/tip20_factory/mod.rs [hunk 2]
```diff
@@ -48,6 +48,19 @@ impl<'a, S: PrecompileStorageProvider> TIP20Factory<'a, S> {
         Ok(info.code.is_some())
     }
 
+    /// Returns true if the address is a valid TIP20 token.
+    ///
+    /// Matches the Solidity implementation which checks both:
+    /// 1. The address has the correct TIP20 prefix
+    /// 2. The token ID (lower 8 bytes) is less than tokenIdCounter
+    pub fn is_tip20(&mut self, token: Address) -> Result<bool> {
+        if !crate::tip20::is_tip20(token) {
```
Comment (0xKitsune) [inline crates/precompiles/src/tip20_factory/mod.rs]: since this only checks prefix, can we rename `is_tip20` to `is_tip20_prefix`?

File: crates/precompiles/src/tip20_factory/mod.rs [hunk 3]
```diff
@@ -48,6 +48,19 @@ impl<'a, S: PrecompileStorageProvider> TIP20Factory<'a, S> {
...
+            return Ok(false);
+        }
+        let token_id = U256::from(address_to_token_id_unchecked(token));
```
Comment (0xKitsune) [inline crates/precompiles/src/tip20_factory/mod.rs]: One additional note, maybe we should add a function called `address_to_token_id` that checks `is_tip20` internally? I imagine there are some places where we are using `address_to_token_id_unchecked` where we would benefit from checking `is_tip20` first. We can do this in a follow on PR.

File: crates/precompiles/src/tip20_factory/dispatch.rs (hunk 1 above)
Comment (fgimenez) [reply crates/precompiles/src/tip20_factory/dispatch.rs:34]: makes sense, gated fix behind allegro moderato and added tests, ptal

File: crates/precompiles/src/tip20_factory/mod.rs (hunk 2 above)
Comment (fgimenez) [reply crates/precompiles/src/tip20_factory/mod.rs]: good call done

File: crates/precompiles/src/tip20_factory/mod.rs (hunk 3 above)
Comment (fgimenez) [reply crates/precompiles/src/tip20_factory/mod.rs]: sure will give it a try

File: crates/precompiles/src/tip20/mod.rs [hunk 4]
```diff
@@ -280,8 +284,26 @@ impl<'a, S: PrecompileStorageProvider> TIP20Token<'a, S> {
         self.check_role(msg_sender, DEFAULT_ADMIN_ROLE)?;
 
         // Verify the new quote token is a valid TIP20 token that has been deployed
-        if !is_tip20(call.newQuoteToken) {
-            return Err(TIP20Error::invalid_quote_token().into());
+        if self.storage.spec().is_allegro_moderato() {
+            // Post-AllegroModerato: use factory's is_tip20 which checks both prefix and counter
```
Comment (0xKitsune) [inline crates/precompiles/src/tip20/mod.rs:288]: Agreed that we should update the spec implementation and the precompile in a follow-on to check that the specified quote token is a valid deployed TIP20 rather than just checking the prefix.

File: crates/precompiles/src/stablecoin_exchange/mod.rs [hunk 5]
```diff
@@ -453,7 +454,7 @@ impl<'a, S: PrecompileStorageProvider> StablecoinExchange<'a, S> {
 
     pub fn create_pair(&mut self, base: Address) -> Result<B256> {
```
Comment (0xKitsune) [inline crates/precompiles/src/stablecoin_exchange/mod.rs:455]: Same thing here, just noting that we should update this in the spec and precompile in a follow on to check that this is a deployed TIP20 rather than just the prefix.

File: crates/precompiles/src/tip20_factory/mod.rs [hunk 6]
```diff
@@ -427,4 +456,57 @@ mod tests {
...
     }
+
+    #[test]
+    fn test_is_tip20_post_allegro_moderato() -> eyre::Result<()> {
+        let mut storage = HashMapStorageProvider::new(1).with_spec(TempoHardfork::AllegroModerato);
+        let sender = Address::random();
+        initialize_path_usd(&mut storage, sender)?;
+
+        let mut factory = TIP20Factory::new(&mut storage);
+        factory.initialize()?;
```
Comment (0xKitsune) [inline crates/precompiles/src/tip20_factory/mod.rs:467]: Can we update this test after [1246](https://github.com/tempoxyz/tempo/pull/1246) is merged to deploy pathUSD from the factory?

File: crates/precompiles/src/tip_fee_manager/mod.rs [hunk 7]
```diff
@@ -114,7 +114,7 @@ impl<'a, S: PrecompileStorageProvider> TipFeeManager<'a, S> {
         call: IFeeManager::setValidatorTokenCall,
         beneficiary: Address,
     ) -> Result<()> {
-        if !is_tip20(call.token) {
+        if !is_tip20_prefix(call.token) {
```
Comment (0xKitsune) [inline crates/precompiles/src/tip_fee_manager/mod.rs:117]: Same here should update spec/precompile in a follow-on.
