### PR TITLE
fix(mempool): ensure fee payer is not blacklisted

### LINKED ISSUE #1110: bug: mempool DOS from blacklisted user
### Describe the bug

the mempool validator only checks if the user has sufficient balance, but does not check if he is allowed to transfer tokens. Because of this, malicious blacklisted users can spam the mempool with transactions, which will fail at the collect_fee_pre_tx function in the handler -> free spamming

### PR DESCRIPTION
**Pull request by 0xrusowsky**
## Motivation

closes #1110 

## Solution

update the tx pool validator to ensure that the fee payer is not blacklisted for the fee token

since the logic is more complex than simply reading a slot, i moved the TIP403 registry internal logic into a fn that takes a closure to perform the sload, so that both are in sync.

PS: I have realized that we read precompile-storage data in several places outside precompiles, so i'll address that in the precompile-refactor PR

### CODE REVIEW

File: crates/precompiles/src/tip403_registry/mod.rs [hunk 1]
```diff
@@ -307,28 +309,58 @@ impl<'a, S: PrecompileStorageProvider> TIP403Registry<'a, S> {
...
+///
+/// # Returns
+/// - `Ok(true)` if the user is authorized
+/// - `Ok(false)` if not authorized or if policy data cannot be decoded
+/// - `Err(E)` if the storage loading operation fails
+pub fn is_authorized_with<E>(
+    policy_id: u64,
+    user: Address,
+    mut load_storage: impl FnMut(U256) -> core::result::Result<U256, E>,
+) -> core::result::Result<bool, E> {
```
Comment (mattsse) [inline crates/precompiles/src/tip403_registry/mod.rs]: this should not need the full path?

File: crates/transaction-pool/src/transaction.rs [hunk 2]
```diff
@@ -109,6 +109,12 @@ pub enum TempoPoolTransactionError {
     )]
     InvalidFeeToken(Address),
 
+    #[error("Fee payer {fee_payer} is blacklisted for fee token: {fee_token}")]
+    BlackListedFeePayer {
```
Comment (mattsse) [inline crates/transaction-pool/src/transaction.rs]: this needs docs, why this happened what this means

File: crates/revm/src/common.rs [hunk 3]
```diff
@@ -200,6 +201,36 @@ pub trait TempoStateAccess<T> {
...
+            tip20::slots::TRANSFER_POLICY_ID_BYTES,
+        ) else {
+            // Should be infallible, but if unable to extract packed value, assume blacklisted.
+            return Ok(false);
+        };
+        self.is_action_authorized(transfer_policy_id, fee_payer)
+    }
+
+    /// Checks if an action is authorized by the TIP403 registry
+    fn is_action_authorized(&mut self, policy_id: u64, user: Address) -> Result<bool, Self::Error> {
```
Comment (mattsse) [inline crates/revm/src/common.rs]: what does action mean here

File: crates/revm/src/common.rs [hunk 4]
```diff
@@ -200,6 +201,36 @@ pub trait TempoStateAccess<T> {
         Ok(self.sload(fee_token, tip20::slots::CURRENCY)? == USD_CURRENCY_SLOT_VALUE)
     }
 
+    /// Checks if the fee payer is not blacklisted for the given token.
+    fn is_valid_fee_payer(
```
Comment (mattsse) [inline crates/revm/src/common.rs]: to be very nitpicky here, we have blacklist vs valid, is this the same or is this different?

File: crates/revm/src/common.rs [hunk 5]
```diff
@@ -200,6 +201,36 @@ pub trait TempoStateAccess<T> {
...
+        // Ensure the fee payer is not blacklisted
+        let Ok(transfer_policy_id) = storage::packing::extract_packed_value(
+            self.sload(fee_token, tip20::slots::TRANSFER_POLICY_ID)?,
+            tip20::slots::TRANSFER_POLICY_ID_OFFSET,
+            tip20::slots::TRANSFER_POLICY_ID_BYTES,
+        ) else {
+            // Should be infallible, but if unable to extract packed value, assume blacklisted.
+            return Ok(false);
+        };
+        self.is_action_authorized(transfer_policy_id, fee_payer)
```
Comment (mattsse) [inline crates/revm/src/common.rs]: this now checks if the transfer policy is authorized, so we're mixing

* valid
* blacklisted
* authorized

and treating this as one and the same, can we unify naming for all of this, because this is a bit confusing, atleast to me

because what this check basically does is "check if the fee payer is authorized to transfer"?

File: crates/precompiles/src/tip403_registry/mod.rs
Comment (mattsse) [inline crates/precompiles/src/tip403_registry/mod.rs:1]: is this change here required for the mempool validation logic?

File: crates/revm/src/common.rs (hunk 3 above)
Comment (0xrusowsky) [reply crates/revm/src/common.rs]: should i rename to call?
basically whatever the policy checks (in this case a transfer, but could be any policy)

File: crates/revm/src/common.rs (hunk 5 above)
Comment (0xrusowsky) [reply crates/revm/src/common.rs]: yes, i only made the policy check its own fn as i thought we may want to reuse it later.

but maybe i was overabstracting

File: crates/precompiles/src/tip403_registry/mod.rs
Comment (0xrusowsky) [reply crates/precompiles/src/tip403_registry/mod.rs:1]: i did it to ensure that both impls are in sync.

as i mentioned in the PR description, the way precompile validations are used outside precompile crates is kinda concerning to me, as we went back to manually reading storage slots (which is error prone and dups code)

i already thought of a solution (after the storage API refactor PR), so maybe it is fine to have dupped logic for the time being, as in the other fns that check precompile state

File: crates/precompiles/src/tip403_registry/mod.rs (hunk 1 above)
Comment (0xrusowsky) [reply crates/precompiles/src/tip403_registry/mod.rs]: all the precompile fns use `crate::error::Result` so otherwise there is a type conflict.

if i leave this as `Result` i need to change all the others

File: crates/revm/src/common.rs (hunk 3 above)
Comment (0xrusowsky) [reply crates/revm/src/common.rs]: dropped the fn completely as it's not needed for anything else for the time being.

addressed in [`082d7f3` (#1114)](https://github.com/tempoxyz/tempo/pull/1114/commits/082d7f3c6b663e218dfb247d01e07f6f13b7708b)

File: crates/revm/src/common.rs (hunk 4 above)
Comment (0xrusowsky) [reply crates/revm/src/common.rs]: renamed to `can_fee_payer_transfer` and made docs more explicit [`082d7f3` (#1114)](https://github.com/tempoxyz/tempo/pull/1114/commits/082d7f3c6b663e218dfb247d01e07f6f13b7708b)

File: crates/revm/src/common.rs (hunk 5 above)
Comment (0xrusowsky) [reply crates/revm/src/common.rs]: dropped the fn completely as it's not needed for anything else for the time being.

addressed in [`082d7f3` (#1114)](https://github.com/tempoxyz/tempo/pull/1114/commits/082d7f3c6b663e218dfb247d01e07f6f13b7708b)

File: crates/transaction-pool/src/validator.rs [hunk 6]
```diff
@@ -742,4 +762,129 @@ mod tests {
             panic!("Expected invalid outcome with InvalidValidAfter error");
         }
     }
+
+    #[tokio::test]
+    async fn test_blacklisted_fee_payer_rejected() {
```
Comment (klkvr) [inline crates/transaction-pool/src/validator.rs:767]: imo we should remove all of those tests and rewrite them as e2e tests that deploy actual tokens

right now most of the test is just configuring the storage manually which is somewhat redundant

can be done in a follow-up though

File: crates/revm/src/common.rs [hunk 7]
```diff
@@ -200,6 +201,71 @@ pub trait TempoStateAccess<T> {
         Ok(self.sload(fee_token, tip20::slots::CURRENCY)? == USD_CURRENCY_SLOT_VALUE)
     }
 
+    /// Checks if the fee payer can transfer a given token (is not blacklisted).
+    fn can_fee_payer_transfer(
```
Comment (klkvr) [inline crates/revm/src/common.rs:205]: yeah we should definitely find a way to unify this

File: crates/transaction-pool/src/validator.rs (hunk 6 above)
Comment (0xKitsune) [reply crates/transaction-pool/src/validator.rs:767]: +1, sgtm to do this in a follow up.

File: crates/revm/src/common.rs [hunk 8]
```diff
@@ -200,6 +201,71 @@ pub trait TempoStateAccess<T> {
...
+        }
+
+        // Ensure the fee payer is not blacklisted
+        let Ok(transfer_policy_id) = storage::packing::extract_packed_value::<1, u64>(
+            self.sload(fee_token, tip20::slots::TRANSFER_POLICY_ID)?,
+            tip20::slots::TRANSFER_POLICY_ID_OFFSET,
+            <u64 as StorableType>::BYTES,
+        ) else {
+            // Should be infallible, but if unable to extract packed value, assume blacklisted.
+            return Ok(false);
```
Comment (0xKitsune) [inline crates/revm/src/common.rs:223]: nit: can we add logging here to warn if this is ever hit? We can also do this in a follow on PR.

File: crates/revm/src/common.rs [hunk 9]
```diff
@@ -200,6 +201,71 @@ pub trait TempoStateAccess<T> {
...
+                    transfer_policy_id.to_be_bytes(),
+                    tip403_registry::slots::POLICY_DATA,
+                ),
+            )?;
+            let Ok(data) = tip403_registry::PolicyData::from_evm_words([policy_data_word]) else {
+                return Ok(false);
+            };
+            let Ok(policy_type) = data.policy_type.try_into() else {
+                return Ok(false);
+            };
```
Comment (0xKitsune) [inline crates/revm/src/common.rs:252]: nit: same thing here we should add proper logging in the case that we hit the else case here. This can be done in a future PR.
