### PR TITLE
fix(primitives): reject AT and ED flags in webauthn validation

### LINKED ISSUE #1008: Bug: Potential for RPC Node DOS by providing bloated webauthn signatures
### Describe the bug

The current node implementation has a potential for RPC Node DOS by providing bloated webauthn signatures which invoke O(n^2) CBOR parsing.

### PR DESCRIPTION
**Pull request by 0xrusowsky**
## Motivation

closes #1008 

## Solution

when performing webauthn validation, reject signatures with the following flags:
- AT: it must NOT be set for assertion signatures (`webauthn.get`)
- ED: we purposely want to deny extensions, as we don't have any usecase for them yet

note: by rejecting extensions, we do not need to worry about CBOR-encoded data

### CODE REVIEW

File: crates/primitives/src/transaction/aa_signature.rs [hunk 1]
```diff
@@ -684,71 +688,51 @@ fn verify_webauthn_data_internal(
...
 
+    let authenticator_data = &webauthn_data[..auth_data_len];
+    let client_data_json = &webauthn_data[auth_data_len..];
+
     // Validate clientDataJSON
     let json_str =
         core::str::from_utf8(client_data_json).map_err(|_| "clientDataJSON is not valid UTF-8")?;
 
+    // Basic JSON structure validation
+    if !json_str.starts_with('{') || !json_str.ends_with('}') {
```
Comment (legion2002) [inline crates/primitives/src/transaction/aa_signature.rs:728]: Why is this validation necessary here? I don't think we do it in the onchain webauthn verifiers.
If we do want to check for clientDataJSON structure, this doesn't seem enough.

File: crates/primitives/src/transaction/aa_signature.rs [hunk 2]
```diff
@@ -684,71 +688,51 @@ fn verify_webauthn_data_internal(
...
+        // If ED flag is not set, exactly 37 bytes (no extensions)
+        MIN_AUTH_DATA_LEN
+    } else {
+        // ED flag must NOT be set, as Tempo AA doesn't support extensions
+        // NOTE: If we ever want to support extensions, we will have to parse CBOR data
+        return Err("ED flag must not be set, as Tempo doesn't support extensions");
+    };
+
+    // Ensure that we have clientDataJSON after authenticatorData
+    if auth_data_len >= webauthn_data.len() {
```
Comment (legion2002) [inline crates/primitives/src/transaction/aa_signature.rs]: This can be removed here, and just added to the check above.

File: crates/primitives/src/transaction/aa_signature.rs [hunk 3]
```diff
@@ -684,71 +688,51 @@ fn verify_webauthn_data_internal(
     webauthn_data: &[u8],
     tx_hash: &B256,
 ) -> Result<B256, &'static str> {
-    // Minimum authenticatorData is 37 bytes (32 rpIdHash + 1 flags + 4 signCount)
-    if webauthn_data.len() < 37 {
+    if webauthn_data.len() < MIN_AUTH_DATA_LEN {
```
Comment (legion2002) [inline crates/primitives/src/transaction/aa_signature.rs]:
```suggestion
    if webauthn_data.len() <= MIN_AUTH_DATA_LEN + 32 {
```

This allows us to remove the clientDataJson check below. This is also a tighter check, because all webauthn data must contain the 37 byte auth data, and the 32 byte tx hash.

File: crates/primitives/src/transaction/aa_signature.rs (hunk 1 above)
Comment (0xrusowsky) [reply crates/primitives/src/transaction/aa_signature.rs:728]: that's the check u had before the patch, i only moved it around.

what do u propose?

Comment (legion2002) [reply crates/primitives/src/transaction/aa_signature.rs:728]: oh okay, I thought this was some audit finding.
Yeah we don't have this check onchain, but I think fine to keep here, it is just an extra layer of validation.
