### PR TITLE
fix(tip20): skip quote token currency check for zero quote token post-AllegroModerato

### LINKED ISSUE #1236: Bug: TIP20 initialization enforces quote token currency for first deployed token
### Describe the bug

Currently, TIP20 [initialization logic ](https://github.com/tempoxyz/tempo/blob/5802d32a4f1873af67d24fa533970d6d1915f38e/crates/precompiles/src/tip20/mod.rs#L746-L753) enforces that if the newly deployed token's currency is `USD`, the quote token specified must also be `USD`.

When deploying the first TIP20, the factory requires that the quote token is `Address::ZERO` and will fail this check if the first token deployed specifies `USD` as the currency.

Tests are currently passing because [initialize_path_usd()](https://github.com/tempoxyz/tempo/blob/5802d32a4f1873af67d24fa533970d6d1915f38e/crates/precompiles/src/tip20/mod.rs#L1009-L1022) sets the currency in storage for the first deployed token. This logic is outdated and we should update `initialize_path_usd` to pass in an initialized factory and deploy the first token instead.

```rust
   /// Takes an initialized TIP20 factory, checks that no tokens have been deployed and deploys pathUSD
    pub(crate) fn deploy_path_usd(
        factory: &mut TIP20Factory,
        admin: Address,
    ) -> Result<()> {
        // --snip-- check that no tokens have been deployed else return an error

       // deploy path usd
       factory.create_token(admin, ITIP20Factory::createTokenCall{"PathUSD", "PathUSD", "USD", Address::ZERO, admin})?;
        )
    }

```

TIP20 initialization logic should be relaxed to skip the quote token currency check for the first deployed token.

```rust
// If the currency is USD, the quote token must also be USD
if currency == USD_CURRENCY {
   let quote_token_currency = TIP20Token::from_address(quote_token).currency()?;

// If the current spec is post allegro moderato and the quote token is zero, skip this check
if self.storage.spec().is_allegro_moderato() && !quote_token.is_zero() {
   if quote_token_currency != USD_CURRENCY {
      return Err(TIP20Error::invalid_quote_token().into());
   }
}
}

```

This is not currently an issue on testnet since PathUSD is already deployed but this should be patched for subsequent deployments.

### PR DESCRIPTION
**Pull request by fgimenez**
Closes #1236

Relaxes TIP20 initialization to allow USD tokens with `Address::ZERO` as quote token when deploying the first token post-AllegroModerato. Previously, the quote token currency check would fail because `Address::ZERO` has no currency stored.

  - Skip quote token currency check in `initialize()` when quote_token is `Address::ZERO` post-AllegroModerato
  - Update `initialize_path_usd` to use factory flow for AllegroModerato+ specs
  - Add `deploy_path_usd` helper for explicit factory-based PathUSD deployment

### CODE REVIEW

File: crates/precompiles/src/tip20/mod.rs [hunk 1]
```diff
@@ -1005,19 +1009,44 @@ pub(crate) mod tests {
...
+        factory.create_token(
             admin,
-            Address::ZERO,
+            ITIP20Factory::createTokenCall {
+                name: "PathUSD".to_string(),
+                symbol: "PUSD".to_string(),
+                currency: "USD".to_string(),
+                quoteToken: Address::ZERO,
+                admin,
+            },
```
Comment (0xKitsune) [inline crates/precompiles/src/tip20/mod.rs:1066]: Can we add a check to ensure that `tokenId == 0` and this is the first token deployed? This will remove any potential footguns when deploying tokens in tests and ensures PathUSD is first. This might already be covered though since `quoteToken: Address::ZERO` but it might be nice to have an easy error to read so we can quickly fix when writing tests rather than having to debug.

File: crates/precompiles/src/tip20/mod.rs [hunk 2]
```diff
@@ -2680,4 +2709,119 @@ pub(crate) mod tests {
...
+            eur_token_address,
+            admin,
+            Address::ZERO,
+        );
+
+        assert!(
+            result.is_err(),
+            "USD token should not be allowed to have a non-USD quote token"
+        );
+    }
```
Comment (0xKitsune) [inline crates/precompiles/src/tip20/mod.rs:2816]: nit: consider aggregating these into `test_initialize_pre_allegro_moderato` and `test_intialize_post_moderato` and asserting usd/non usd conditions in each.

File: crates/precompiles/src/tip20/mod.rs (hunk 1 above)
Comment (fgimenez) [reply crates/precompiles/src/tip20/mod.rs:1066]: ok, returning now `TIP20Error::invalid_quote_token()` in case token id != 0

File: crates/precompiles/src/tip20/mod.rs (hunk 2 above)
Comment (fgimenez) [reply crates/precompiles/src/tip20/mod.rs:2816]: sure done
