### PR TITLE
fix: clear prev order + test

### LINKED ISSUE #1007: Bug: `fill_order` does not clear `Order.prev`
Severity: Medium
Status: Open

**Notes:** ✅

### PR DESCRIPTION
**Pull request by 0xrusowsky**
## Motivation

closes #1007 

## Solution

clear previous order when an order is filled

### CODE REVIEW

File: crates/precompiles/src/stablecoin_exchange/mod.rs [hunk 1]
```diff
@@ -1524,78 +1525,82 @@ mod tests {
...
 
-        // Initialize base token  and mint amount
+    fn setup_test_tokens<S: PrecompileStorageProvider>(
+        storage: &mut S,
+        admin: Address,
+        user: Address,
+        exchange_address: Address,
+        amount: u128,
+    ) -> (Address, Address) {
+        // Initialize quote token (LinkingUSD)
```
Comment (fgimenez) [inline crates/precompiles/src/stablecoin_exchange/mod.rs]: this might need to be aligned with https://github.com/tempoxyz/tempo/pull/1015, maybe gating behind allegretto, wdyt @0xKitsune

File: crates/precompiles/src/stablecoin_exchange/mod.rs [hunk 2]
```diff
@@ -802,6 +802,7 @@ impl<'a, S: PrecompileStorageProvider> StablecoinExchange<'a, S> {
         } else {
             // If there are subsequent orders at tick, advance to next order
             level.head = order.next();
+            Order::update_prev_order(self, order.next(), 0)?;
```
Comment (klkvr) [inline crates/precompiles/src/stablecoin_exchange/mod.rs]: should this be gated behind Allegretto?

File: crates/precompiles/src/stablecoin_exchange/mod.rs (hunk 1 above)
Comment (0xKitsune) [reply crates/precompiles/src/stablecoin_exchange/mod.rs]: Yes this should be aligned with 1015 which updates linkingUSD to pathUSD. I don't think we need to gate anything here since this is for tests.

File: crates/precompiles/src/stablecoin_exchange/mod.rs (hunk 2 above)
Comment (0xKitsune) [reply crates/precompiles/src/stablecoin_exchange/mod.rs]: Yes this needs to be gated behind Allegretto.

File: crates/precompiles/src/stablecoin_exchange/mod.rs [hunk 3]
```diff
@@ -4118,4 +4125,58 @@ mod tests {
 
         Ok(())
     }
+
+    #[test]
+    // https://github.com/tempoxyz/tempo/issues/1007
+    fn test_audit_issue_1007() -> eyre::Result<()> {
```
Comment (0xKitsune) [inline crates/precompiles/src/stablecoin_exchange/mod.rs]: nit: can we rename to `test_clear_order_post_allegretto` or similar? We can still link the above issue.
