### PR TITLE
fix(precompiles): enforce TIP20 blacklist on internal balance operations in StablecoinExchange

### LINKED ISSUE #1288: Blacklisted users can extract value from the StablecoinExchange by operating entirely on internal balances
### Describe the bug

ref https://tempoxyz.slack.com/archives/C09PGSBNXFG/p1764913784505099

When decrement_balance_or_transfer_from() is called during order placement (line 438) or swaps (line 255), users with sufficient internal balance only have their accounting decremented via sub_balance() at line 197 - no TIP20 transfer occurs, therefore no blacklist check.

### Steps to reproduce

N/A

### Logs

```text

```

### Platform(s)

_No response_

### Container Type

Not running in a container

### What version/commit are you on?

da49fd8cb0aca41837e1e82249fed437d20e3a8d

### If you've built from source, provide the full command you used

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by fgimenez**
Closes #1288 

Adds blacklist authorization check in `decrement_balance_or_transfer_from()` before operating on internal balances. Previously, users with sufficient internal balance bypassed TIP20 transfer policy checks since no actual token transfer occurred.

### CODE REVIEW

File: crates/precompiles/src/stablecoin_exchange/mod.rs [hunk 1]
```diff
@@ -264,13 +264,29 @@ impl<'a, S: PrecompileStorageProvider> StablecoinExchange<'a, S> {
...
 
+    fn ensure_transfer_authorized(&mut self, token: Address, user: Address) -> Result<()> {
+        if token == PATH_USD_ADDRESS {
+            PathUSD::new(self.storage)
+                .token
+                .ensure_transfer_authorized(user, self.address)?;
+        } else {
+            TIP20Token::from_address(token, self.storage)?
+                .ensure_transfer_authorized(user, self.address)?;
+        }
```
Comment (0xKitsune) [inline crates/precompiles/src/stablecoin_exchange/mod.rs]: Now that PathUSD is treated like any other TIP20, we can just use `TIP20Token::from_address(token, self.storage)?.ensure_transfer_authorized(user, self.address)?;`. With this in mind, we probably can also remove the extra `ensure_transfer_authorized` function and jus tuse `TIP20.ensure_transfer_authorized` inline instead.

Comment (fgimenez) [reply crates/precompiles/src/stablecoin_exchange/mod.rs]: sure done

**Review by howydev — APPROVED** [review]

**Review by legion2002 — COMMENTED** [review]
@fgimenez Pushed the solidity spec changes and tests for this.
Currently the precompile fuzz tests don't work because allegro moderato is not active on tempo-foundry.

Discussing with the foundry team what's the best workflow solution here.
CC: @grandizzy

File: crates/precompiles/src/stablecoin_exchange/mod.rs [hunk 2]
```diff
@@ -4284,4 +4289,93 @@ mod tests {
             Ok(())
         })
     }
+
+    #[test]
+    fn test_blacklisted_user_cannot_use_internal_balance() -> eyre::Result<()> {
```
Comment (0xKitsune) [inline crates/precompiles/src/stablecoin_exchange/mod.rs:4295]: Can we update this test to use the new `StorageCtx` approach? You can check out other tests in this mod for reference.

File: crates/precompiles/src/stablecoin_exchange/mod.rs [hunk 3]
```diff
@@ -4284,4 +4289,93 @@ mod tests {
...
+        let mut base = TIP20Token::new(1, quote.token.storage());
+        base.initialize("BASE", "BASE", "USD", quote_address, admin, Address::ZERO)?;
+        base.grant_role_internal(admin, *ISSUER_ROLE)?;
+        let base_address = base.address();
+        base.change_transfer_policy_id(
+            admin,
+            ITIP20::changeTransferPolicyIdCall {
+                newPolicyId: policy_id,
+            },
+        )?;
```
Comment (0xKitsune) [inline crates/precompiles/src/stablecoin_exchange/mod.rs]: We can use the new [TIP20Setup in the test_util mod](https://github.com/tempoxyz/tempo/blob/main/crates/precompiles/src/test_util.rs#L201-L230) to simplify this.

File: docs/specs/src/StablecoinExchange.sol [hunk 4]
```diff
@@ -220,6 +223,15 @@ contract StablecoinExchange is IStablecoinExchange {
...
             }
 
+            // Check if maker is authorized by the token's transfer policy before operating on internal balance
+            uint64 policyId = ITIP20(escrowToken).transferPolicyId();
+            if (
+                !TIP403_REGISTRY.isAuthorized(policyId, maker)
+                    || !TIP403_REGISTRY.isAuthorized(policyId, address(this))
+            ) {
+                revert ITIP20.PolicyForbids();
+            }
```
Comment (0xKitsune) [inline docs/specs/src/StablecoinExchange.sol:233]: It might be nice to update the `TIP20` contract  expose an `isAuthorized` function in a subsequent PR. Any thoughts @howydev @legion2002?

File: crates/precompiles/src/stablecoin_exchange/mod.rs (hunk 2 above)
Comment (fgimenez) [reply crates/precompiles/src/stablecoin_exchange/mod.rs:4295]: sure done

File: crates/precompiles/src/stablecoin_exchange/mod.rs (hunk 3 above)
Comment (fgimenez) [reply crates/precompiles/src/stablecoin_exchange/mod.rs]: yep, already done as part of the StorageCtx refactor, ptal

File: docs/specs/src/StablecoinExchange.sol (hunk 4 above)
Comment (howydev) [reply docs/specs/src/StablecoinExchange.sol:233]: Could see it being useful for defi, but would be a lower priority for now. If we have a tracking list, can add to that
