### PR TITLE
fix(commonware-node): remove malachite args

### LINKED ISSUE #204: Tempo commonware contains malachite args
The tempo commonware binary contains the malachite args because it uses `TempoArgs` when setting up its clap parser.

This causes the parser to refuse continuing, while returning confusing messages noting that `--consensus-config` option being absent even though the user provided it.

### PR DESCRIPTION
**Pull request by SuperFluffy**
Removes the malachite args from the tempo commonware node command line options.

This is a implemented as a workaround because `TempoNode::new` requires `TempoArgs`, but we don't want the tempo arguments to appear in the CLI parser.

Closes #204

### CODE REVIEW

File: bin/tempo-commonware/src/main.rs [hunk 1]
```diff
@@ -115,15 +121,17 @@ fn main() -> eyre::Result<()> {
...
         .run_with_components::<TempoNode>(components, async move |builder, args| {
-            let faucet_args = args.inner.faucet_args.clone();
+            let faucet_args = args.faucet_args.clone();
 
             let NodeHandle {
                 node,
                 node_exit_future,
             } = builder
-                .node(TempoNode::new(args.inner.clone()))
+                // TODO: simplify this after the malachite bits have been removed.
```
Comment (mattsse) [inline bin/tempo-commonware/src/main.rs:132]: right, ideally this should be the same args type?

Comment (SuperFluffy) [reply bin/tempo-commonware/src/main.rs:132]: I am ambivalent - I think `TempoNode::new` should only contain arguments relevant to the execution layer (i.e. `faucet_args`) so that we have a cleaner separation between consensus and execution parts of the node.

But our setup is such that most of the logic flows through the reth cli setup, so it's a bit roundabout.
